<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spectrum128kEmulator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="obj\**\*.cs" />
    <Compile Remove="bin\**\*.cs" />
    <Compile Remove="tmp\**\*.cs" />
    <EmbeddedResource Remove="obj\**\*" />
    <EmbeddedResource Remove="bin\**\*" />
    <EmbeddedResource Remove="tmp\**\*" />
    <None Remove="obj\**\*" />
    <None Remove="bin\**\*" />
    <None Remove="tmp\**\*" />
  </ItemGroup>
</Project>
